void HDRFilm::save(const std::string &filename, float *ptr)
{
std::cout << "Writing a " << mWidth << "x" << mHeight
<< " OpenEXR file to \"" << filename << "\"" << std::endl;

Imf::Header header((int)mWidth, (int)mHeight);

header.insert("comments", Imf::StringAttribute("Generated by the
Galactica Renderer (Kider)"));

Imf::ChannelList &channels = header.channels();
channels.insert("R", Imf::Channel(Imf::FLOAT));
channels.insert("G", Imf::Channel(Imf::FLOAT));
channels.insert("B", Imf::Channel(Imf::FLOAT));

Imf::FrameBuffer frameBuffer;

size_t compStride = sizeof(float),

pixelStride = 4 * compStride, rowStride = pixelStride * (int)mWidth;

char* Cptr = reinterpret_cast<char *>(ptr);

frameBuffer.insert("R", Imf::Slice(Imf::FLOAT, Cptr, pixelStride,
rowStride)); 

Cptr += compStride;

frameBuffer.insert("G", Imf::Slice(Imf::FLOAT, Cptr, pixelStride,
rowStride)); 

Cptr += compStride;

frameBuffer.insert("B", Imf::Slice(Imf::FLOAT, Cptr, pixelStride, rowStride));

Imf::OutputFile file(filename.c_str(), header);

file.setFrameBuffer(frameBuffer);

file.writePixels((int)mHeight);
}